### ISSUE TITLE
Security issue in JSON5 caught by npm when installing eslint package

### ISSUE THREAD

**Issue by jwithington** [btholt/complete-intro-to-react-v8#51]
In the Hooks Q&A video, we run: 
`npm install -D eslint-plugin-react-hooks@4.6.0.`

This found a vulnerability in one of the dependencies (see below).

<img width="830" alt="CleanShot 2022-12-29 at 13 03 22@2x" src="https://user-images.githubusercontent.com/4213550/210011006-00a1cbab-df8e-4f60-abd6-2fda0b3ec253.png">

link:
https://github.com/advisories/GHSA-9c47-m6qq-7p4h

**Comment by jwithington** [comment]
although also possible it's not actually a vulnerability:
https://github.com/import-js/eslint-plugin-import/pull/2624

**Comment by dtauer** [comment]
Thanks for the heads up. Brian mentions in the course that package vulnerabilities may come up, but since this isn't a production app, it's not a big deal. He intentionally pins these versions during the course so they will still work in the future so we don't often modify any package versions after the fact. But thanks for reporting this!
