### ISSUE TITLE
Uncontrolled forms - why not pass animal state in the submission

### ISSUE THREAD

**Issue by jordan-bott** [btholt/complete-intro-to-react-v8#92]
I've just finished the Uncontrolled Forms video and was curious why we use `formData.get("animal")` when creating the object for `setRequestParams`. I believe this is a mistake in the video, but Brian says to leave `value={animal}`, however I had to change this to `name="animal"` to get the `formData.get()` to work properly. Apologies if I missed where he mentioned to change to name, I watched a few times and couldn't see it in the video, but did find it in the lecture notes. 

This leads me to my main question - rather than using `formData` for animal, would it make more sense to pass in the `animal` state since we are tracking it? I'm imagining the object changing to: 
```
const obj = {
            animal: animal,
            breed: formData.get("breed") ?? "",
            location: formData.get("location") ?? "",
          }
```
Mostly, I am just curious what the best practice would be / pitfalls of the two different ways. To me, it seems like using the state, and leaving `value={animal}` would make the most sense, that way the form is correctly showing the tracked state, and the submission is correctly using the state, but would love to hear other thoughts.

**Comment by dtauer** [comment]
Great questions, Jordan. The form functionality should still work with `value={animal}`. And that needs to stay reactive in the form because the breed dropdown is depending on there being a selected animal. That's the main reason Brian said you need to leave that in.

As for the formData -- When this property is created from the `new FormData(e.target)`, it's using the `name` attribute from each form field to create the formData properties. This is why you need to add the `name` attribute. But as I said above, it should still work with the `value={animal}` attribute as well.

I'm not sure if this completely answers your questions, but the general benefit of uncontrolled forms is that you are leveraging the native form behavior from the browser. And once the form is submitted, you're using the FormData API (which is just a JavaScript API) to pull out the data.

Let me know if that answers your question!
